title:              ArifRawf.github.io
email:              armanbdd@gmail.com
description:        We Provide Free Tips And Tricks To Let You Explore The Internet More Sharper.
author:             Arif Rawf
baseurl:            ""
url:                "https://ArifRawf.github.io"

# Social Profiles
twitter_username:   Arif Rawf
github_username:    ArifRawf
facebook_username:  Arif Rawf
instagram_username:  Arif Rawf
linkedin_username: Arif Rawf

# Add your google-analytics ID here to activate google analytics
 # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           10
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
